database:
  - name: pgsql
    host: localhost
    port: 5432
    dbname: postgres
    user: postgres
    password: postgres
embedding:
  - name: openai
    api_key: sk-1234abcd
    model: text-embedding-ada-002
llm:
  - name: openai
    api_key: sk-1234abcd
    model: gpt-3.5-turbo
resource:
  - name: docsdir
    path: docs
prompt: |
  You are a question answering bot for a open source project.
  Always answer questions in the language of the questioner.
guide: |
  Please refer to the following to answer the questions:
  """
  %s
  """
server:
  host: 0.0.0.0
  port: 8181
  debug: false